# Permalinks

# Setup
title:            blog
description:      "kmh's writings, mostly about cybersecurity"
url:              https://kmh.zone/blog
baseurl:          /blog

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5
